#!/usr/bin/env node

const jsdom = require('jsdom');
const axios = require('axios');
const path = require('path');
const open = require('open');

const { JSDOM } = jsdom;

const FOOTBALL_BASE_URL = 'https://live-stream365.com';
const FOOTBALL_URL_PATH = '/sport/football.php';

const findTeamLink = (document, team) => [...document.querySelectorAll('a')]
  .find(el => el.textContent.toLowerCase().includes(team.toLowerCase()));

const fetchGamesListHTML = async () => (await axios.get(`${FOOTBALL_BASE_URL}${FOOTBALL_URL_PATH}`)).data;

const getFootballLink = async (team) => {
  const dom = new JSDOM(`<!DOCTYPE html>${await fetchGamesListHTML()}`);
  const linkEl = findTeamLink(dom.window.document, team);

  if (!linkEl) {
    throw new Error(`Link for team '${team}' cannot be found`);
  }

  return `${FOOTBALL_BASE_URL}${linkEl.getAttribute('onclick').match(/open\('([^\']+)'/)[1]}`
};

function usage(err) {
  err && console.log(`Error: ${err.message}`);

  console.log(`\nUsage: ${path.basename(process.argv[1])} command`);
  console.log('\nCOMMANDS');
  console.log('    list         Lists the available games and current result');
  console.log('    play         plays the football with provided team name on browser');
  console.log('\nEXAMPLES');
  console.log(`   ${path.basename(process.argv[1])} play liverpool\n`);

  process.exit(1);
}

async function excuteCommand(commandName, params = {}) {
  if (commandName === 'play') {
    if (!params.team) {
      throw new Error('No team name is entered');
    }

    const gameLink = await getFootballLink(params.team);
    await open(gameLink, {app: ['firefox', '-private-window']});
  } else if (commandName === 'list') {
    const dom = new JSDOM(`<!DOCTYPE html>${await fetchGamesListHTML()}`);
    const { window: { document } } = dom;
    const formattedReport = [...document.querySelectorAll('table.sort1 tr')].slice(1).map(({children}) => `${children[2].textContent}: ${children[4].textContent}`).join('\n');

    console.log(formattedReport);
  }
}

async function main() {
  if (process.argv.length < 3) {
    throw new Error('No commands are specified');
  }

  const command = process.argv[2];

  if (command === 'list') {
    await excuteCommand(command);
  } else if (command === 'play') {
    await excuteCommand(command, { team: process.argv[3] });
  } else {
    throw new Error(`Invalid command name: ${command}`);
  }
}

(async () => {
  try {
    await main();
  } catch(err) {
    usage(err);
  }
})();
